name: "build"

on:
  pull_request:
    branches:
      - "master"
      - "stable"
  push:
    branches:
      - "master"
      - "stable"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "setup go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.18"
      - name: "go vet"
        run: "go vet -v ./..."
      - name: "go test"
        run: "go test -v ./..."
      - name: "go build"
        run: "go build ./"
